import { describe, expect, it } from 'vitest'
import fs from 'node:fs'
import path from 'node:path'

describe('App source', () => {
  it('renders fixed desktop shell with top bar and 1/8-6/8-1/8 layout', () => {
    const source = fs.readFileSync(path.resolve(process.cwd(), 'renderer/src/App.vue'), 'utf8')

    expect(source).toContain('AppTopBar')
    expect(source).toContain('WorkspaceSidebar')
    expect(source).toContain('DesignWorkspace')
    expect(source).toContain('TaskManagerSidebar')
    expect(source).toContain('shell-grid')
    expect(source).toContain('shell-grid__sidebar')
    expect(source).toContain('shell-grid__workspace')
    expect(source).toContain('shell-grid__tasks')
    expect(source).toContain('秋 Ai')
    expect(source).toContain('暗黑')
    expect(source).toContain('明亮')
    expect(source).toContain('护眼')
    expect(source).toContain('getStudioSnapshot')
    expect(source).toContain('saveSettings')
    expect(source).toContain('showActionFeedback')
    expect(source).toContain('buildErrorMessage')
    expect(source).toContain('app-notice-layer')
    expect(source).toContain('成功')
    expect(source).toContain('失败')
    expect(source).toContain('resetDraftForMenu')
    expect(source).toContain('resetActiveDraftAfterSubmit')
  })

  it('uses six fixed sidebar menu items and comment placeholders for UI events', () => {
    const source = fs.readFileSync(path.resolve(process.cwd(), 'renderer/src/components/WorkspaceSidebar.vue'), 'utf8')

    expect(source).toContain('工作台')
    expect(source).toContain('文案设计')
    expect(source).toContain('单图测试')
    expect(source).toContain('单图设计')
    expect(source).toContain('套图设计')
    expect(source).toContain('套图生成')
    expect(source).toContain('模型价格')
    expect(source).toContain("key: 'workspace'")
    expect(source).toContain("key: 'copywriting'")
    expect(source).toContain("key: 'single-image'")
    expect(source).toContain("key: 'single-design'")
    expect(source).toContain("key: 'series-design'")
    expect(source).toContain("key: 'series-generate'")
    expect(source).toContain("key: 'model-pricing'")
    expect(source).toContain('菜单点击事件预留')
  })

  it('renders task sidebar with fixed categories and statuses', () => {
    const source = fs.readFileSync(path.resolve(process.cwd(), 'renderer/src/components/TaskManagerSidebar.vue'), 'utf8')

    expect(source).toContain('任务队列')
    expect(source).toContain('文案设计')
    expect(source).toContain('单图测试')
    expect(source).toContain('单图设计')
    expect(source).toContain('套图设计')
    expect(source).toContain('套图生成')
    expect(source).toContain('等待中')
    expect(source).toContain('进行中')
    expect(source).toContain('已完成')
    expect(source).toContain('失败')
    expect(source).toContain('任务编号')
    expect(source).toContain('生成时间')
    expect(source).toContain('formatTaskNumber')
    expect(source).toContain('10 个任务')
    expect(source).toContain('上一页')
    expect(source).toContain('下一页')
    expect(source).toContain('currentPage')
    expect(source).toContain('ResultExportPanel')
    expect(source).toContain('showWorkspaceTasks')
    expect(source).toContain('showExportPanel')
    expect(source).toContain('当前页面暂无侧边内容')
  })

  it('renders dashboard workspace, single-block model pricing, and three-panel design pages', () => {
    const source = fs.readFileSync(path.resolve(process.cwd(), 'renderer/src/components/DesignWorkspace.vue'), 'utf8')

    expect(source).toContain('WorkspaceDashboard')
    expect(source).toContain("activeMenu === 'workspace'")
    expect(source).toContain('ParameterSettingsPanel')
    expect(source).toContain('ResultDisplayPanel')
    expect(source).not.toContain('ResultExportPanel')
    expect(source).toContain("activeMenu === 'model-pricing'")
    expect(source).toContain('workspace-panels--single')
    expect(source).toContain('workspace-panels--focus-display')
    expect(source).toContain('single-design')
    expect(source).toContain('latestTask')
  })

  it('defines classified model pools for copywriting and image generation', () => {
    const source = fs.readFileSync(path.resolve(process.cwd(), 'renderer/src/App.vue'), 'utf8')

    expect(source).toContain('const copywritingModelOptions = [')
    expect(source).toContain('gemini-3-pro')
    expect(source).toContain('gemini-3.1-pro')
    expect(source).toContain('const imageModelOptions = [')
    expect(source).toContain('nano-banana-fast')
    expect(source).toContain('nano-banana-pro-4k-vip')
    expect(source).toContain('const currentModelOptions = computed(() => {')
    expect(source).toContain("if (activeMenu.value === 'copywriting')")
    expect(source).toContain('currentModelOptions')
  })

  it('wires copywriting image upload actions through the workspace shell', () => {
    const appSource = fs.readFileSync(path.resolve(process.cwd(), 'renderer/src/App.vue'), 'utf8')
    const workspaceSource = fs.readFileSync(path.resolve(process.cwd(), 'renderer/src/components/DesignWorkspace.vue'), 'utf8')

    expect(workspaceSource).toContain('select-copywriting-images')
    expect(workspaceSource).toContain('clear-copywriting-images')
    expect(appSource).toContain('handleSelectCopywritingImages')
    expect(appSource).toContain('handleClearCopywritingImages')
    expect(appSource).toContain('handleSelectSingleImage')
    expect(appSource).toContain('handleOpenSingleImagePicker')
    expect(workspaceSource).toContain('select-single-design-image')
    expect(appSource).toContain('handleSelectSingleDesignImage')
    expect(appSource).toContain('handleOpenSingleDesignImagePicker')
    expect(appSource).toContain('handleSelectSeriesDesignImages')
    expect(appSource).toContain('handleOpenSeriesDesignPicker')
    expect(appSource).toContain('handleSelectSeriesGenerateImage')
    expect(appSource).toContain('handleOpenSeriesGeneratePicker')
    expect(appSource).toContain('copyMode')
    expect(appSource).toContain('referenceImages')
    expect(appSource).not.toContain('handleImportCopywritingFile')
    expect(appSource).not.toContain('handleOpenCopywritingImportPicker')
    expect(appSource).not.toContain('copywritingImportInput')
  })

  it('wires export panel output-directory action through the desktop bridge', () => {
    const appSource = fs.readFileSync(path.resolve(process.cwd(), 'renderer/src/App.vue'), 'utf8')
    const taskSidebarSource = fs.readFileSync(path.resolve(process.cwd(), 'renderer/src/components/TaskManagerSidebar.vue'), 'utf8')

    expect(taskSidebarSource).toContain('open-output-directory')
    expect(taskSidebarSource).toContain('exportItems')
    expect(taskSidebarSource).toContain('selectedExportIds')
    expect(appSource).toContain('handleOpenOutputDirectory')
    expect(appSource).toContain('openOutputDirectory')
    expect(appSource).toContain('latestTaskForActiveMenu')
  })
})
