import { describe, expect, it } from 'vitest'
import fs from 'node:fs'
import path from 'node:path'

describe('App source', () => {
  it('renders fixed desktop shell with theme switch, notice layer and retained drafts after submit', () => {
    const source = fs.readFileSync(path.resolve(process.cwd(), 'renderer/src/App.vue'), 'utf8')
    const preloadSource = fs.readFileSync(path.resolve(process.cwd(), 'main/preload.js'), 'utf8')

    expect(source).toContain('AppTopBar')
    expect(source).toContain('ActivationGate')
    expect(source).toContain('WorkspaceSidebar')
    expect(source).toContain('DesignWorkspace')
    expect(source).toContain('TaskManagerSidebar')
    expect(source).toContain('shell-grid')
    expect(source).toContain('getStudioSnapshot')
    expect(source).toContain('getActivationStatus')
    expect(source).toContain('saveSettings')
    expect(source).toContain('showActionFeedback')
    expect(source).toContain('buildErrorMessage')
    expect(source).toContain('buildTaskFailureFeedbackMessage')
    expect(source).toContain('openClearRuntimeConfirm')
    expect(source).toContain('confirmClearRuntimeState')
    expect(source).toContain('@cleanup-click="openClearRuntimeConfirm"')
    expect(source).toContain('scheduleDraftPersist')
    expect(source).toContain('hasActiveStudioTasks')
    expect(source).toContain('activationState')
    expect(source).toContain('replaceDraft')
    expect(source).toContain('AdminPasswordDialog')
    expect(source).toContain('AdminApiKeyDialog')
    expect(source).toContain('listNegativePromptTemplates')
    expect(source).toContain('saveNegativePromptTemplate')
    expect(source).toContain('removeNegativePromptTemplate')
    expect(source).toContain('negativePromptTemplates')
    expect(source).toContain('loadNegativePromptTemplateState')
    expect(source).toContain('applyNegativeTemplateSelection')
    expect(source).toContain("field === 'negativeTemplateId'")
    expect(source).toContain('resolveTemplatePromptValue')
    expect(source).toContain('previousTemplatePrompt: currentTemplate?.prompt || \'\'')
    expect(source).toContain('nextTemplatePrompt: matchedTemplate?.prompt || \'\'')
    expect(preloadSource).not.toContain('PROMPT_TAGS_LIST')
    expect(preloadSource).not.toContain('PROMPT_TAGS_SAVE_CATEGORY')
  })

  it('uses prompt library sidebar item together with studio menus without copywriting', () => {
    const sidebarSource = fs.readFileSync(path.resolve(process.cwd(), 'renderer/src/components/WorkspaceSidebar.vue'), 'utf8')
    const appSource = fs.readFileSync(path.resolve(process.cwd(), 'renderer/src/App.vue'), 'utf8')

    expect(sidebarSource).toContain("key: 'workspace'")
    expect(sidebarSource).toContain("key: 'single-image'")
    expect(sidebarSource).toContain("key: 'single-design'")
    expect(sidebarSource).toContain("key: 'series-design'")
    expect(sidebarSource).toContain("key: 'series-generate'")
    expect(sidebarSource).toContain("key: 'model-pricing'")
    expect(sidebarSource).toContain("key: 'prompt-library'")
    expect(sidebarSource).not.toContain("key: 'copywriting'")
    expect(appSource).toContain("{ key: 'prompt-library', label: '提示词库' }")
  })

  it('renders task sidebar with workspace queue and design export modes only', () => {
    const source = fs.readFileSync(path.resolve(process.cwd(), 'renderer/src/components/TaskManagerSidebar.vue'), 'utf8')

    expect(source).toContain('stop-task')
    expect(source).toContain('isStoppableTask')
    expect(source).toContain('ResultExportPanel')
    expect(source).toContain('showWorkspaceTasks')
    expect(source).toContain('showExportPanel')
    expect(source).toContain('downloadCleanupEnabled')
    expect(source).toContain('toggle-download-cleanup')
    expect(source).not.toContain("props.activeMenu === 'prompt-library'")
    expect(source).not.toContain("props.activeMenu === 'copywriting'")
  })

  it('renders dashboard workspace, prompt library, single-block model pricing, and focus display design pages', () => {
    const source = fs.readFileSync(path.resolve(process.cwd(), 'renderer/src/components/DesignWorkspace.vue'), 'utf8')

    expect(source).toContain('WorkspaceDashboard')
    expect(source).toContain("activeMenu === 'workspace'")
    expect(source).toContain('PromptLibraryPanel')
    expect(source).toContain("activeMenu === 'prompt-library'")
    expect(source).toContain('ParameterSettingsPanel')
    expect(source).toContain('ResultDisplayPanel')
    expect(source).not.toContain('ResultExportPanel')
    expect(source).toContain("activeMenu === 'model-pricing'")
    expect(source).toContain('workspace-panels--single')
    expect(source).toContain('workspace-panels--focus-display')
    expect(source).toContain(':prompt-templates="allPromptTemplates"')
    expect(source).toContain(':custom-prompt-templates="customPromptTemplates"')
    expect(source).toContain(':fixed-negative-prompt-templates="fixedNegativePromptTemplates"')
    expect(source).toContain(':custom-negative-prompt-templates="customNegativePromptTemplates"')
  })

  it('defines image-generation model pools and shared prompt-template defaults', () => {
    const source = fs.readFileSync(path.resolve(process.cwd(), 'renderer/src/App.vue'), 'utf8')
    const draftStateSource = fs.readFileSync(path.resolve(process.cwd(), 'renderer/src/utils/studioDraftState.js'), 'utf8')

    expect(source).not.toContain('const copywritingModelOptions = [')
    expect(source).toContain('const imageModelOptions = [')
    expect(source).toContain('nano-banana-fast')
    expect(source).toContain('nano-banana-pro-4k-vip')
    expect(source).toContain('const currentModelOptions = computed(() => {')
    expect(source).toContain('const allPromptTemplates = computed(() => {')
    expect(source).toContain('Math.min(500')
    expect(source).toContain('currentLongRunningHint')
    expect(source).toContain('currentTaskScaleSummary')
    expect(source).toContain('normalizeBatchPrompts')
    expect(source).toContain('differentialEnabled')
    expect(source).toContain('batchPrompts')
    expect(source).toContain('resolveTaskScaleSummary')
    expect(source).toContain("if (currentTaskScaleSummary.value?.level === 'block')")
    expect(source).toContain("} from '../../shared/promptTemplateDefaults.mjs'")
    expect(source).toContain('DEFAULT_EMPTY_PROMPT_TEMPLATE_ID')
    expect(source).toContain('DEFAULT_EMPTY_NEGATIVE_TEMPLATE_ID')
    expect(source).toContain("import {\n  createDefaultActivationState,")
    expect(source).toContain("} from './utils/studioDraftState'")
    expect(draftStateSource).toContain("prompt: ''")
    expect(source).toContain("negativeTemplateId: String(draft.negativeTemplateId || DEFAULT_EMPTY_NEGATIVE_TEMPLATE_ID)")
    expect(draftStateSource).toContain("templateId: currentAssignment.templateId || DEFAULT_EMPTY_PROMPT_TEMPLATE_ID")
    expect(source).toContain("templateId: DEFAULT_EMPTY_PROMPT_TEMPLATE_ID")
    expect(draftStateSource).toContain("imageType: currentAssignment.imageType || ''")
    expect(draftStateSource).toContain("imageType: assignment.imageType || ''")
    expect(source).toContain("imageType: ''")
    expect(source).toContain("return promptTemplates.value.filter((item) => item.source === 'system-fixed')")
    expect(source).toContain("return negativePromptTemplates.value.filter((item) => item.source === 'system-fixed')")
    expect(source).not.toContain('filterInvalidSelectedGlobalTagIds')
    expect(source).not.toContain('cleanupDraftSelectedGlobalTags')
    expect(source).toContain('await persistDraftPatch(menuKey, nextDraft)')
    expect(source).not.toContain('legacyGlobalPrompt')
  })

  it('defines a recharge catalog for the model pricing page', () => {
    const source = fs.readFileSync(path.resolve(process.cwd(), 'renderer/src/App.vue'), 'utf8')

    expect(source).toContain('const rechargePricingCatalog = [')
    expect(source).toContain(':recharge-pricing-catalog="rechargePricingCatalog"')
  })

  it('keeps only needed pricing models and orders them by ascending credits', () => {
    const source = fs.readFileSync(path.resolve(process.cwd(), 'renderer/src/App.vue'), 'utf8')

    expect(source).not.toContain("name: 'gemini-3-pro'")
    expect(source).not.toContain("name: 'sora-create-character'")
    expect(source.indexOf("name: 'nano-banana-fast'")).toBeLessThan(source.indexOf("name: 'gpt-image-2'"))
    expect(source.indexOf("name: 'gpt-image-2'")).toBeLessThan(source.indexOf("name: 'nano-banana-2'"))
  })

  it('wires image upload actions through the workspace shell', () => {
    const appSource = fs.readFileSync(path.resolve(process.cwd(), 'renderer/src/App.vue'), 'utf8')
    const assetStateSource = fs.readFileSync(path.resolve(process.cwd(), 'renderer/src/utils/studioAssetState.js'), 'utf8')
    const workspaceSource = fs.readFileSync(path.resolve(process.cwd(), 'renderer/src/components/DesignWorkspace.vue'), 'utf8')

    expect(appSource).toContain('pickStudioInputAssets')
    expect(appSource).toContain('uploadDirectoryDrafts')
    expect(appSource).toContain('handleUploadDirectoryDraftUpdate')
    expect(appSource).toContain('handleSaveUploadDirectory')
    expect(appSource).toContain('handleOpenSingleImagePicker')
    expect(appSource).toContain('handleOpenSingleDesignImagePicker')
    expect(appSource).toContain('handleOpenSeriesDesignPicker')
    expect(appSource).toContain('handleOpenSeriesGeneratePicker')
    expect(appSource).toContain("} from './utils/studioAssetState'")
    expect(appSource).toContain('saveSettings({')
    expect(appSource).toContain('uploadDirectories:')
    expect(appSource).not.toContain('globalUploadDirectory')
    expect(assetStateSource).toContain('createEmptyUploadDirectoryDrafts')
    expect(assetStateSource).toContain('normalizeUploadDirectoryDrafts')
    expect(assetStateSource).toContain('createImageAsset')
    expect(assetStateSource).toContain('revokeDraftPreviews')
    expect(workspaceSource).toContain('save-upload-directory')
    expect(workspaceSource).toContain('update-upload-directory-draft')
  })

  it('wires export panel output-directory action through the desktop bridge', () => {
    const appSource = fs.readFileSync(path.resolve(process.cwd(), 'renderer/src/App.vue'), 'utf8')
    const taskSidebarSource = fs.readFileSync(path.resolve(process.cwd(), 'renderer/src/components/TaskManagerSidebar.vue'), 'utf8')

    expect(taskSidebarSource).toContain('open-output-directory')
    expect(taskSidebarSource).toContain('stop-task')
    expect(appSource).toContain('handleOpenOutputDirectory')
    expect(appSource).toContain('handleStopTask')
    expect(appSource).toContain('stopStudioTask')
    expect(appSource).toContain('openOutputDirectory')
    expect(appSource).toContain('latestTaskForActiveMenu')
  })

  it('only shows latest task progress for the active menu instead of falling back to other modules', () => {
    const source = fs.readFileSync(path.resolve(process.cwd(), 'renderer/src/App.vue'), 'utf8')

    expect(source).toContain("const matchedTask = sortedTasks.value.find((task) => task.menuKey === activeMenu.value)")
    expect(source).toContain('return matchedTask || null')
    expect(source).not.toContain('return matchedTask || sortedTasks.value[0] || null')
  })

  it('optimistically updates queued task state after submit instead of waiting on a full snapshot refresh', () => {
    const source = fs.readFileSync(path.resolve(process.cwd(), 'renderer/src/App.vue'), 'utf8')

    expect(source).toContain('function upsertTaskIntoState(task)')
    expect(source).toContain('const createdTask = await createStudioTask({')
    expect(source).toContain('upsertTaskIntoState(createdTask)')
    expect(source).toContain('buildDraftForSubmit')
    expect(source).toContain("globalPrompt: String(draft.globalPrompt || '')")
    expect(source).toContain('detectPromptRisk')
    expect(source).toContain('void refreshStudioRuntimeState()')
    expect(source).toContain('handleFailedTaskNotifications')
    expect(source).toContain('previousTaskStatusMap')
    expect(source).toContain('handleRefreshDashboardTotalCredits')
    expect(source).toContain('handleRefreshDashboardRemainingCredits')
    expect(source).toContain('refreshDashboardCredits')
    expect(source).toContain("target: 'total'")
    expect(source).toContain("target: 'remaining'")
  })

  it('persists the export auto-cleanup preference and deletes selected folders after successful download', () => {
    const source = fs.readFileSync(path.resolve(process.cwd(), 'renderer/src/App.vue'), 'utf8')

    expect(source).toContain('downloadCleanupEnabled')
    expect(source).toContain('handleToggleDownloadCleanup')
    expect(source).toContain('downloadCleanupEnabled: value')
    expect(source).toContain('const exportedIds = [...selectedExportIds.value]')
    expect(source).toContain('if (downloadCleanupEnabled.value)')
    expect(source).toContain('Promise.allSettled(exportedIds.map((exportItemId) => deleteStudioExportItem({')
  })

  it('preserves export folder checkbox choices across refreshes while auto-selecting only new items', () => {
    const source = fs.readFileSync(path.resolve(process.cwd(), 'renderer/src/App.vue'), 'utf8')

    expect(source).toContain('const selectedExportIdsByMenu = ref(createEmptyExportSelectionsByMenu(menuItems))')
    expect(source).toContain("createEmptyExportSelectionsByMenu,\n  createEmptyHostInfo,")
    expect(source).toContain('function syncSelectedExportIdsForMenu(menuKey)')
    expect(source).toContain('const previousSelection = new Set(selectedExportIdsByMenu.value[menuKey] || [])')
    expect(source).toContain('selectedExportIdsByMenu.value = {')
    expect(source).toContain('[menuKey]: nextSelectedIds')
  })

  it('bumps a reset key after one-key cleanup so parameter inputs remount against the cleared drafts', () => {
    const appSource = fs.readFileSync(path.resolve(process.cwd(), 'renderer/src/App.vue'), 'utf8')
    const workspaceSource = fs.readFileSync(path.resolve(process.cwd(), 'renderer/src/components/DesignWorkspace.vue'), 'utf8')

    expect(appSource).toContain('const runtimeResetSequence = ref(0)')
    expect(appSource).toContain('runtimeResetSequence.value += 1')
    expect(appSource).toContain(':runtime-reset-sequence="runtimeResetSequence"')
    expect(workspaceSource).toContain(":key=\"`${activeMenu}-${runtimeResetSequence}`\"")
  })

  it('uses an in-app confirmation dialog for one-key cleanup while leaving task actions on native confirm', () => {
    const appSource = fs.readFileSync(path.resolve(process.cwd(), 'renderer/src/App.vue'), 'utf8')

    expect(appSource).toContain('isClearRuntimeConfirmVisible.value = true')
    expect(appSource).toContain('isClearRuntimeConfirmVisible.value = false')
    expect(appSource).toContain(':is-clear-runtime-confirm-visible="isClearRuntimeConfirmVisible"')
    expect(appSource).toContain('@confirm-clear-runtime-state="confirmClearRuntimeState"')
  })
})
