import { describe, expect, it } from 'vitest'
import fs from 'node:fs'
import path from 'node:path'

describe('component sources', () => {
  it('contains top bar, parameter, effect and export panel placeholders without copywriting blocks', () => {
    const appSource = fs.readFileSync(path.resolve(process.cwd(), 'renderer/src/App.vue'), 'utf8')
    const activationSource = fs.readFileSync(path.resolve(process.cwd(), 'renderer/src/components/ActivationGate.vue'), 'utf8')
    const topbarSource = fs.readFileSync(path.resolve(process.cwd(), 'renderer/src/components/AppTopBar.vue'), 'utf8')
    const parameterSource = fs.readFileSync(path.resolve(process.cwd(), 'renderer/src/components/ParameterSettingsPanel.vue'), 'utf8')
    const resultSource = fs.readFileSync(path.resolve(process.cwd(), 'renderer/src/components/ResultDisplayPanel.vue'), 'utf8')
    const exportSource = fs.readFileSync(path.resolve(process.cwd(), 'renderer/src/components/ResultExportPanel.vue'), 'utf8')
    const dashboardSource = fs.readFileSync(path.resolve(process.cwd(), 'renderer/src/components/WorkspaceDashboard.vue'), 'utf8')
    const promptLibrarySource = fs.readFileSync(path.resolve(process.cwd(), 'renderer/src/components/PromptLibraryPanel.vue'), 'utf8')

    expect(activationSource).toContain('设备码')
    expect(activationSource).toContain('复制设备码')
    expect(activationSource).toContain('导入授权文件')
    expect(activationSource).toContain('刷新校验')
    expect(activationSource).toContain('activationState')
    expect(activationSource).toContain('已激活')

    expect(topbarSource).toContain('Logo 点击事件预留')
    expect(topbarSource).toContain('主题切换事件预留')
    expect(topbarSource).toContain('一键清理按钮点击事件预留')
    expect(topbarSource).toContain('微信 / 企业微信图片预览切换')
    expect(topbarSource).toContain('一键清理')
    expect(topbarSource).toContain('v-if="themeOptions.length > 1"')
    expect(topbarSource).toContain('weixin.png')
    expect(topbarSource).toContain('qiyeweixin.png')
    expect(topbarSource).toContain('Qiushui.jpg')
    expect(topbarSource).toContain('Dockerfans.jpg')
    expect(topbarSource).toContain('Qiyeweixin.jpg')
    expect(topbarSource).toContain('微信')
    expect(topbarSource).toContain('企业微信')
    expect(topbarSource).toContain('topbar-contact-button')
    expect(topbarSource).toContain('contact-preview-modal')
    expect(topbarSource).toContain('closeContactPreview')
    expect(topbarSource).toContain('activationSummary')
    expect(topbarSource).toContain('已激活')
    expect(topbarSource).toContain('topbar-right-actions')
    expect(topbarSource.indexOf('topbar-activation-pill')).toBeLessThan(topbarSource.indexOf('topbar-clean-button'))
    expect(topbarSource.indexOf('topbar-clean-button')).toBeLessThan(topbarSource.indexOf('topbar-contact-actions'))

    expect(parameterSource).toContain('提交任务事件预留')
    expect(parameterSource).toContain('scrollbar-hidden')
    expect(parameterSource).toContain('任务名称')
    expect(parameterSource).toContain('默认打开目录')
    expect(parameterSource).toContain('保存目录')
    expect(parameterSource).toContain('upload-directory-row')
    expect(parameterSource).toContain('upload-directory-input')
    expect(parameterSource).toContain('提示词输入区域')
    expect(parameterSource).toContain('模型选择')
    expect(parameterSource).toContain('shangchuan.png')
    expect(parameterSource).toContain('baocun.png')
    expect(parameterSource).toContain('daoru.png')
    expect(parameterSource).toContain('moban.png')
    expect(parameterSource).toContain('对比模型 1')
    expect(parameterSource).toContain('对比模型 4')
    expect(parameterSource).toContain('设计模型')
    expect(appSource).toContain('A4 竖版')
    expect(appSource).toContain('A4 横版')
    expect(appSource).toContain('A5 竖版')
    expect(appSource).toContain('A5 横版')
    expect(appSource).toContain('8K 横版')
    expect(appSource).toContain('8K 竖版')
    expect(parameterSource).toContain('全局主提示词')
    expect(parameterSource).toContain('图片专属提示词')
    expect(parameterSource).toContain('生成组数')
    expect(parameterSource).toContain('全局风格提示词')
    expect(parameterSource).toContain('生成数量')
    expect(parameterSource).toContain('批次')
    expect(parameterSource).toContain('逐张提示词配置')
    expect(parameterSource).toContain('第 ${index + 1} 张')
    expect(parameterSource).toContain('图片类型')
    expect(parameterSource).toContain('商品主图')
    expect(parameterSource).toContain('详情图')
    expect(parameterSource).toContain('细节图')
    expect(parameterSource).toContain('尺寸图')
    expect(parameterSource).toContain('白底图')
    expect(parameterSource).toContain('颜色图')
    expect(parameterSource).toContain('导入')
    expect(parameterSource).toContain('select-icon-field')
    expect(parameterSource).toContain('select-icon-field__icon')
    expect(parameterSource).toContain('customPromptTemplates')
    expect(parameterSource).toContain('请选择要补充的提示词模板')
    expect(parameterSource).toContain('补充到当前提示词')
    expect(parameterSource).toContain('number-stepper')
    expect(parameterSource).toContain('stepper-button stepper-button--decrement')
    expect(parameterSource).toContain('stepper-button stepper-button--increment')
    expect(parameterSource).toContain('stepper-button__triangle--left')
    expect(parameterSource).toContain('stepper-button__triangle--right')
    expect(parameterSource).toContain("stepField('generateCount', draftForm.generateCount, -1, 1, 100)")
    expect(parameterSource).toContain("updateStepperField('generateCount', $event.target.value, 1, 100)")
    expect(parameterSource).toContain("stepField('batchCount', draftForm.batchCount, -1, 1, 9999)")
    expect(parameterSource).toContain("updateStepperField('batchCount', $event.target.value, 1, 9999)")
    expect(parameterSource).toContain('submitButtonState')
    expect(parameterSource).toContain('提交成功√')
    expect(parameterSource).not.toContain("activeMenu === 'copywriting'")
    expect(parameterSource).not.toContain('select-copywriting-images')
    expect(parameterSource).not.toContain('clear-copywriting-images')
    expect(parameterSource).not.toContain('单独提示词')
    expect(parameterSource).not.toContain('文案类型')
    expect(parameterSource).not.toContain('批量输入方式')
    expect(parameterSource).not.toContain('批量内容')
    expect(parameterSource).not.toContain('逐行输入')
    expect(parameterSource).not.toContain('导入 TXT')
    expect(parameterSource).not.toContain('导入 CSV')
    expect(parameterSource).not.toContain("{{ menuLabel }} / {{ menuHint }}")
    expect(parameterSource).not.toContain('不上传图片则直接按文生图处理，上传后自动按图生图处理。')
    expect(parameterSource).not.toContain('固定模型，优先用于稳定快速对比')
    expect(parameterSource).not.toContain('固定模型，作为标准效果参考')
    expect(parameterSource).not.toContain('示例：选中 3 张图，生成组数为 3，则最终输出 3 组完整套图。')

    expect(resultSource).toContain("activeMenu === 'model-pricing'")
    expect(resultSource).toContain('积分充值')
    expect(resultSource).toContain('section-title section-title--centered')
    expect(resultSource).toContain('recharge-price-grid')
    expect(resultSource).toContain('recharge-price-card')
    expect(resultSource).toContain('recharge-price-card__ribbon')
    expect(resultSource).toContain('rechargePricingCatalog')
    expect(resultSource).toContain('model-price-grid')
    expect(resultSource).toContain('model-price-card')
    expect(resultSource).toContain('gpt-image-2')
    expect(resultSource).not.toContain('{{ model.price }}')
    expect(resultSource).not.toContain('¥0.15~¥0.3 / 次')
    expect(resultSource).toContain('空状态占位')
    expect(resultSource).toContain('效果展示')
    expect(resultSource).toContain('任务进度')
    expect(resultSource).toContain('latestTask')
    expect(resultSource).toContain('latest-task-progress')
    expect(resultSource).toContain('当前组')
    expect(resultSource).toContain('组内进度')
    expect(resultSource).toContain('panel-content--display-scroll')
    expect(resultSource).toContain('scrollbar-hidden')
    expect(resultSource).toContain('group-output-grid--scroll')
    expect(resultSource).toContain('四模型效果对比')
    expect(resultSource).toContain('单模型效果展示')
    expect(resultSource).toContain('comparison-grid comparison-grid--single comparison-grid--adaptive')
    expect(resultSource).toContain('comparison-card comparison-card--adaptive')
    expect(resultSource).toContain('批次输出')
    expect(resultSource).toContain('result-group-card__elapsed')
    expect(resultSource).toContain('下载图片')
    expect(resultSource).toContain('preview-modal')
    expect(resultSource).not.toContain('文本结果')
    expect(resultSource).not.toContain("showCopywriting")

    expect(exportSource).toContain('批量下载')
    expect(exportSource).not.toContain('批量选择性下载')
    expect(exportSource).toContain('复选框')
    expect(exportSource).toContain('itemCount')
    expect(exportSource).toContain('wenjianjia.png')
    expect(exportSource).toContain('down.png')
    expect(exportSource).toContain('shanchu.png')
    expect(exportSource).toContain('delete-export-item')
    expect(exportSource).toContain('handleDeleteExportItem')
    expect(exportSource).toContain('open-output-directory')
    expect(exportSource).toContain('export-item__toggle')
    expect(exportSource).toContain('export-item__actions')
    expect(exportSource).toContain('export-download-button')
    expect(exportSource).toContain('scrollbar-hidden')
    expect(exportSource).toContain('const pageSize = 8')
    expect(exportSource).toContain('pagedExportItems')
    expect(exportSource).toContain('totalPages')
    expect(exportSource).toContain('export-pagination')
    expect(exportSource).toContain('pagination-arrow-button')
    expect(exportSource).toContain('pagination-arrow-button__triangle--left')
    expect(exportSource).toContain('pagination-arrow-button__triangle--right')
    expect(exportSource).toContain('aria-label="上一页"')
    expect(exportSource).toContain('aria-label="下一页"')
    expect(exportSource).toContain('个图片')
    expect(exportSource).not.toContain('个结果文件')

    const taskSidebarSource = fs.readFileSync(path.resolve(process.cwd(), 'renderer/src/components/TaskManagerSidebar.vue'), 'utf8')
    expect(taskSidebarSource).toContain('结束任务')
    expect(taskSidebarSource).toContain('stop-task')
    expect(taskSidebarSource).toContain('isStoppableTask')
    expect(taskSidebarSource).toContain('task-card__footer')

    expect(dashboardSource).not.toContain('文案生成统计')
    expect(dashboardSource).toContain('单图测试统计')
    expect(dashboardSource).toContain('单图设计统计')
    expect(dashboardSource).toContain('套图设计统计')
    expect(dashboardSource).toContain('套图生成统计')
    expect(dashboardSource).toContain('全局 API-Key 配置')
    expect(dashboardSource).toContain('用户主机信息')
    expect(dashboardSource).toContain('积分仪表盘')
    expect(dashboardSource).toContain('积分消息记录')
    expect(dashboardSource).toContain('网络监控')
    expect(dashboardSource).toContain('networkMonitorCard')
    expect(dashboardSource).toContain('networkMonitorPoints')
    expect(dashboardSource).toContain('dashboard-network-monitor')
    expect(dashboardSource).toContain('dashboard-column--stats-stack')
    expect(dashboardSource).toContain('dashboard-column__stack')
    expect(dashboardSource).toContain('最近请求延迟')
    expect(dashboardSource).toContain('dashboard-network-monitor__polyline')
    expect(dashboardSource).toContain('dashboard-network-monitor__metric')
    expect(dashboardSource).not.toContain('最近 12 次请求')
    expect(dashboardSource).toContain('剩余积分')
    expect(dashboardSource).toContain('总积分')
    expect(dashboardSource).toContain('调整积分')
    expect(dashboardSource).toContain('增加积分')
    expect(dashboardSource).toContain('扣减积分')
    expect(dashboardSource).toContain('creditGaugeGlow')
    expect(dashboardSource).toContain('creditGaugeProgress')
    expect(dashboardSource).toContain('dashboard-credit-gauge')
    expect(dashboardSource).toContain('dashboard-credit-gauge__arc dashboard-credit-gauge__arc--active')
    expect(dashboardSource).toContain('dashboard-credit-gauge__value')
    expect(dashboardSource).toContain('{{ remainingCredits }} / {{ totalCredits }}')
    expect(dashboardSource).toContain('#38d9ff')
    expect(dashboardSource).toContain('#4ade80')
    expect(dashboardSource).toContain('#ff5f6d')
    expect(dashboardSource).not.toContain('creditNeedleRotation')
    expect(dashboardSource).not.toContain('creditGaugeMarkers')
    expect(dashboardSource).not.toContain('dashboard-credit-gauge__ticks')
    expect(dashboardSource).not.toContain('dashboard-credit-gauge__marker-labels')
    expect(dashboardSource).not.toContain('dashboard-credit-gauge__scale')
    expect(dashboardSource).not.toContain('dashboard-credit-gauge__needle')
    expect(dashboardSource).not.toContain('dashboard-credit-gauge__needle-cap')
    expect(dashboardSource).not.toContain('<span>0%</span>')
    expect(dashboardSource).not.toContain('<span>100%</span>')
    expect(dashboardSource).not.toContain("label: '25%'")
    expect(dashboardSource).not.toContain("label: '50%'")
    expect(dashboardSource).not.toContain("label: '75%'")
    expect(dashboardSource).not.toContain('当前档位')
    expect(dashboardSource).not.toContain('最近变动')
    expect(dashboardSource).not.toContain('冻结积分')
    expect(dashboardSource).not.toContain('已用积分')
    expect(dashboardSource).toContain('creditAdjustmentValue')
    expect(dashboardSource).toContain('totalCreditsValue')
    expect(dashboardSource).toContain('isSavingTotalCredits')
    expect(dashboardSource).toContain('dashboard-credit-adjust__grid')
    expect(dashboardSource).toContain('dashboard-credit-adjust__actions')
    expect(dashboardSource).toContain('secondary-action secondary-action--compact')
    expect(dashboardSource).toContain('creditMessagesCard')
    expect(dashboardSource).toContain('workspaceDashboard.creditMessages')
    expect(dashboardSource).toContain('dashboard-credit-message-list')
    expect(dashboardSource).toContain('apply-credit-adjustment')
    expect(dashboardSource).toContain('save-total-credits')
    expect(dashboardSource).toContain('模型调用次数')
    expect(dashboardSource).toContain('API-Key 1')
    expect(dashboardSource).toContain('API-Key 2')
    expect(dashboardSource).toContain('启用 Key 1')
    expect(dashboardSource).toContain('启用 Key 2')
    expect(dashboardSource).toContain('保存配置')
    expect(dashboardSource).not.toContain('接口节点')
    expect(dashboardSource).not.toContain('apiBaseUrl')
    expect(dashboardSource).not.toContain('国内节点')
    expect(dashboardSource).not.toContain('海外节点')

    expect(promptLibrarySource).toContain('按钮提示词')
    expect(promptLibrarySource).toContain('自定义提示词')
    expect(promptLibrarySource).toContain('商品主图')
    expect(promptLibrarySource).toContain('按钮名称')
    expect(promptLibrarySource).toContain('按钮预览')
    expect(promptLibrarySource).toContain('toggleTemplateExpansion')
    expect(promptLibrarySource).toContain('toggleStoredTemplateExpansion')
    expect(promptLibrarySource).toContain('expandedFixedTemplateIds')
    expect(promptLibrarySource).toContain('expandedStoredTemplateIds')
    expect(promptLibrarySource).toContain('prompt-library-column__body scrollbar-hidden')
    expect(promptLibrarySource).toContain('prompt-template-disclosure')
    expect(promptLibrarySource).toContain('prompt-storage-card__summary')
    expect(promptLibrarySource).toContain('保存按钮提示词')
    expect(promptLibrarySource).toContain('提示词存储')
    expect(promptLibrarySource).toContain('按模板名称排序')
    expect(promptLibrarySource).toContain('localeCompare')
    expect(promptLibrarySource).toContain('新建自定义模板')
    expect(promptLibrarySource).toContain('保存模板')
    expect(promptLibrarySource).toContain('删除模板')
    expect(promptLibrarySource).toContain('system-fixed')
    expect(promptLibrarySource).toContain('custom')
    expect(promptLibrarySource).not.toContain('system-fixed / 商品主图 / 详情图 / 细节图 / 尺寸图 / 白底图 / 颜色图')
  })
})
