import { describe, expect, it } from 'vitest'
import fs from 'node:fs'
import path from 'node:path'

describe('component sources', () => {
  it('contains top bar and panel placeholders for theme, logo, wechat and downloads', () => {
    const topbarSource = fs.readFileSync(path.resolve(process.cwd(), 'renderer/src/components/AppTopBar.vue'), 'utf8')
    const parameterSource = fs.readFileSync(path.resolve(process.cwd(), 'renderer/src/components/ParameterSettingsPanel.vue'), 'utf8')
    const resultSource = fs.readFileSync(path.resolve(process.cwd(), 'renderer/src/components/ResultDisplayPanel.vue'), 'utf8')
    const exportSource = fs.readFileSync(path.resolve(process.cwd(), 'renderer/src/components/ResultExportPanel.vue'), 'utf8')
    const dashboardSource = fs.readFileSync(path.resolve(process.cwd(), 'renderer/src/components/WorkspaceDashboard.vue'), 'utf8')

    expect(topbarSource).toContain('Logo 点击事件预留')
    expect(topbarSource).toContain('主题切换事件预留')
    expect(topbarSource).toContain('微信按钮点击事件预留')
    expect(parameterSource).toContain('提交任务事件预留')
    expect(parameterSource).toContain('scrollbar-hidden')
    expect(parameterSource).toContain('提示词输入区域')
    expect(parameterSource).toContain('模型选择')
    expect(parameterSource).toContain('任务名称')
    expect(parameterSource).toContain('参考图片')
    expect(parameterSource).toContain('shangchuan.png')
    expect(parameterSource).toContain('数量')
    expect(parameterSource).toContain('对比模型 1')
    expect(parameterSource).toContain('对比模型 4')
    expect(parameterSource).toContain('不上传图片则直接按文生图处理')
    expect(parameterSource).toContain('设计模型')
    expect(parameterSource).toContain('全局主提示词')
    expect(parameterSource).toContain('图片专属提示词')
    expect(parameterSource).toContain('生成组数')
    expect(parameterSource).toContain('全局风格提示词')
    expect(parameterSource).toContain('生成数量')
    expect(parameterSource).toContain('逐张提示词配置')
    expect(parameterSource).toContain('第 ${index + 1} 张')
    expect(parameterSource).toContain('number-stepper')
    expect(parameterSource).toContain('stepper-button stepper-button--decrement')
    expect(parameterSource).toContain('stepper-button stepper-button--increment')
    expect(parameterSource).toContain('stepper-button__triangle--left')
    expect(parameterSource).toContain('stepper-button__triangle--right')
    expect(parameterSource.indexOf('stepper-button stepper-button--decrement')).toBeLessThan(parameterSource.indexOf('stepper-value'))
    expect(parameterSource.indexOf('stepper-value')).toBeLessThan(parameterSource.indexOf('stepper-button stepper-button--increment'))
    expect(parameterSource).not.toContain('当前模块')
    expect(parameterSource).not.toContain('文案类型')
    expect(parameterSource).not.toContain('批量输入方式')
    expect(parameterSource).not.toContain('批量内容')
    expect(parameterSource).not.toContain('逐行输入')
    expect(parameterSource).not.toContain('导入 TXT')
    expect(parameterSource).not.toContain('导入 CSV')
    expect(parameterSource).not.toContain('最多上传 30 张图片，选中的图片才会进入替换生图。')
    expect(parameterSource).not.toContain('建议不超过 20 次。')
    expect(parameterSource).not.toContain('<span>风格要求</span>')
    expect(parameterSource).not.toContain('单轮生成数量')
    expect(parameterSource).not.toContain('批次数量')
    expect(parameterSource.indexOf('任务名称')).toBeLessThan(parameterSource.indexOf('参考图片'))
    expect(parameterSource.indexOf('参考图片')).toBeLessThan(parameterSource.indexOf('提示词输入区域'))
    expect(parameterSource).toContain('submitButtonState')
    expect(parameterSource).toContain('提交成功√')
    expect(resultSource).toContain("activeMenu === 'model-pricing'")
    expect(resultSource).toContain('model-price-grid')
    expect(resultSource).toContain('model-price-card')
    expect(resultSource).toContain('3000 / 次')
    expect(resultSource).toContain('¥0.15~¥0.3 / 次')
    expect(resultSource).toContain('gpt-image-2')
    expect(resultSource).toContain('空状态占位')
    expect(resultSource).toContain('效果展示')
    expect(resultSource).toContain('任务进度')
    expect(resultSource).toContain('latestTask')
    expect(resultSource).toContain('latest-task-progress')
    expect(resultSource).toContain('panel-content--display-scroll')
    expect(resultSource).toContain('scrollbar-hidden')
    expect(resultSource).toContain('group-output-grid--scroll')
    expect(resultSource).toContain('文本结果')
    expect(resultSource).toContain('四模型效果对比')
    expect(resultSource).toContain('单模型效果展示')
    expect(resultSource).toContain('批次输出')
    expect(resultSource).toContain('result-group-card__elapsed')
    expect(resultSource).toContain('下载图片')
    expect(resultSource).toContain('preview-modal')
    expect(resultSource).toContain('生成耗时')
    expect(resultSource).not.toContain('按批次整组输出')
    expect(resultSource).not.toContain('按批次分组输出')
    expect(resultSource).not.toContain('summary-metrics')
    expect(resultSource).not.toContain('promptSummary')
    expect(resultSource).not.toContain('已完成')
    expect(exportSource).toContain('批量下载')
    expect(exportSource).not.toContain('批量选择性下载')
    expect(exportSource).toContain('复选框')
    expect(exportSource).toContain('itemCount')
    expect(exportSource).toContain('baocun.png')
    expect(exportSource).toContain('down.png')
    expect(exportSource).toContain('shanchu.png')
    expect(exportSource).toContain('delete-export-item')
    expect(exportSource).toContain('handleDeleteExportItem')
    expect(exportSource).toContain('open-output-directory')
    expect(exportSource).toContain('export-item__actions')
    expect(exportSource).toContain('export-download-button')
    expect(exportSource).toContain('scrollbar-hidden')
    expect(exportSource).not.toContain('等待生成真实文件夹路径')
    expect(dashboardSource).toContain('文案生成统计')
    expect(dashboardSource).toContain('套图设计统计')
    expect(dashboardSource).toContain('单图测试统计')
    expect(dashboardSource).toContain('套图生成统计')
    expect(dashboardSource).toContain('全局 API-Key 配置')
    expect(dashboardSource).toContain('用户主机信息')
    expect(dashboardSource).toContain('模型调用次数')
    expect(dashboardSource).toContain('API-Key 1')
    expect(dashboardSource).toContain('API-Key 2')
    expect(dashboardSource).toContain('启用 Key 1')
    expect(dashboardSource).toContain('启用 Key 2')
    expect(dashboardSource).toContain('保存配置')
    expect(dashboardSource).not.toContain('接口节点')
    expect(dashboardSource).not.toContain('apiBaseUrl')
    expect(dashboardSource).not.toContain('国内节点')
    expect(dashboardSource).not.toContain('海外节点')
    expect(dashboardSource).not.toContain('本地已存在可用 API-Key')
  })
})
