import { describe, expect, it } from 'vitest'
import fs from 'node:fs'
import path from 'node:path'

describe('styles source', () => {
  it('contains fixed shell, internal scroll areas and three themes', () => {
    const source = fs.readFileSync(path.resolve(process.cwd(), 'renderer/src/assets/styles.css'), 'utf8')

    expect(source).toContain("[data-theme='dark']")
    expect(source).toContain("[data-theme='light']")
    expect(source).toContain("[data-theme='eye-care']")
    expect(source).toContain('.app-shell')
    expect(source).toContain('flex-direction: column;')
    expect(source).toContain('height: 100vh;')
    expect(source).toContain('.shell-grid')
    expect(source).toContain('flex: 1;')
    expect(source).toContain('grid-template-columns: minmax(0, 1fr) minmax(0, 6fr) minmax(0, 1fr);')
    expect(source).toContain('.shell-grid__sidebar')
    expect(source).toContain('.shell-grid__workspace')
    expect(source).toContain('.shell-grid__tasks')
    expect(source).toContain('.app-notice-layer')
    expect(source).toContain('.app-notice')
    expect(source).toContain('.app-notice--success')
    expect(source).toContain('.app-notice--error')
    expect(source).toContain('overflow: hidden;')
    expect(source).toContain('.module-scroll')
    expect(source).toContain('overflow: hidden;')
    expect(source).toContain('.scrollbar-hidden')
    expect(source).toContain('.scrollbar-hidden::-webkit-scrollbar')
    expect(source).toContain('.panel-content--scrollable')
    expect(source).toContain('overflow-y: auto;')
  })

  it('contains workspace focus layout, paged task sidebar and task state styles', () => {
    const source = fs.readFileSync(path.resolve(process.cwd(), 'renderer/src/assets/styles.css'), 'utf8')

    expect(source).toContain('.workspace-panels')
    expect(source).toContain('grid-template-columns: repeat(3, minmax(0, 1fr));')
    expect(source).toContain('.workspace-panels--single')
    expect(source).toContain('grid-template-columns: minmax(0, 1fr);')
    expect(source).toContain('.workspace-panels--focus-display')
    expect(source).toContain('minmax(280px, 1fr) minmax(0, 1.8fr);')
    expect(source).toContain('.workspace-panel')
    expect(source).toContain('.workspace-dashboard')
    expect(source).toContain('.dashboard-column')
    expect(source).toContain('.dashboard-stat-card')
    expect(source).toContain('.dashboard-config-card')
    expect(source).toContain('.dashboard-stat-list')
    expect(source).toContain('grid-template-columns: repeat(2, minmax(0, 1fr));')
    expect(source).toContain('.dashboard-column--split > *')
    expect(source).toContain('height: 100%;')
    expect(source).toContain('.dashboard-info-list')
    expect(source).toContain('.workspace-dashboard__inner')
    expect(source).toContain('padding: 14px;')
    expect(source).toContain('.task-status--waiting')
    expect(source).toContain('.task-status--running')
    expect(source).toContain('.task-status--completed')
    expect(source).toContain('.task-status--failed')
    expect(source).toContain('.task-progress__bar')
    expect(source).toContain('.task-list--paged')
    expect(source).toContain('.task-pagination')
    expect(source).toContain('.task-sidebar-empty')
    expect(source).toContain('.task-sidebar-shell--card')
    expect(source).toContain('@media (max-width: 1680px)')
    expect(source).toContain('@media (max-width: 1360px)')
    expect(source).toContain('min-width: 0;')
    expect(source).toContain('.model-price-grid')
    expect(source).toContain('grid-template-columns: repeat(auto-fit, minmax(180px, 1fr));')
    expect(source).toContain('.model-price-card')
    expect(source).toContain('.panel-content--export-scroll')
    expect(source).toContain('.panel-content--display-scroll')
    expect(source).toContain('.export-download-button')
    expect(source).toContain('width: 100%;')
    expect(source).toContain('.export-item__actions')
    expect(source).toContain('justify-content: flex-end;')
    expect(source).toContain('.comparison-grid')
    expect(source).toContain('grid-template-columns: repeat(auto-fit, minmax(190px, 1fr));')
    expect(source).toContain('.group-output-grid--scroll')
    expect(source).toContain('.result-group-card__elapsed')
    expect(source).toContain('grid-auto-flow: column;')
    expect(source).toContain('overflow-x: auto;')
    expect(source).toContain('.latest-task-progress')
    expect(source).toContain('.latest-task-progress__bar')
    expect(source).toContain('gap: clamp(10px, 1vw, 14px);')
  })
})
