const DEFAULT_EMPTY_PROMPT_TEMPLATE_ID = 'system-empty-image-type'
const DEFAULT_EMPTY_PROMPT_TEMPLATE_NAME = '无类型图片'
const DEFAULT_EMPTY_NEGATIVE_TEMPLATE_ID = 'system-empty-negative-prompt'
const DEFAULT_EMPTY_NEGATIVE_TEMPLATE_NAME = '无负向提示词'

exports.DEFAULT_EMPTY_PROMPT_TEMPLATE_ID = DEFAULT_EMPTY_PROMPT_TEMPLATE_ID
exports.DEFAULT_EMPTY_PROMPT_TEMPLATE_NAME = DEFAULT_EMPTY_PROMPT_TEMPLATE_NAME
exports.DEFAULT_EMPTY_NEGATIVE_TEMPLATE_ID = DEFAULT_EMPTY_NEGATIVE_TEMPLATE_ID
exports.DEFAULT_EMPTY_NEGATIVE_TEMPLATE_NAME = DEFAULT_EMPTY_NEGATIVE_TEMPLATE_NAME

module.exports = {
  DEFAULT_EMPTY_PROMPT_TEMPLATE_ID,
  DEFAULT_EMPTY_PROMPT_TEMPLATE_NAME,
  DEFAULT_EMPTY_NEGATIVE_TEMPLATE_ID,
  DEFAULT_EMPTY_NEGATIVE_TEMPLATE_NAME
}
